#!/bin/bash

# description: the go web server 
# processname: webserver 

BIN_PATH=/opt/jp/bin
SERVICE=$BIN_PATH/webserver
PID_FILE=/var/run/webserver.pid

function launchDaemon() {
    local id
    checkRunning
    id=$?
    if [ $id -eq 0 ]
    then
        touch $PID_FILE
        cd $BIN_PATH
        $SERVICE > /dev/null 2>&1 & echo $! > $PID_FILE
        echo "webserver started"
    else
        echo "webserver is running already"
    fi
}

function stopDaemon() {
    local is_running
    local id
    checkRunning
    is_running=$?
    if [ $is_running -eq 1 ]
    then
        id=`cat $PID_FILE`
        kill $id
        if [ $? -eq 0 ]
        then
            echo "webserver stopped"
        else
            echo "Unable to stop webserver"
        fi
    else
        echo "webserver is stopped already"
    fi
}

function checkRunning() {
    local id
    id=`cat $PID_FILE`
    if [ -z $id ]
    then
        return 0
    elif [ -d "/proc/$id" ]
    then
        return 1
    else
        return 0
    fi
}

function main {
    local is_running
    case "$1" in
    start)
        launchDaemon
    ;;
    stop)
        stopDaemon
    ;;
    restart)
        stopDaemon
        sleep 1
        launchDaemon
    ;;
    status)
        checkRunning
        is_running=$?
        if [ $is_running -eq 1 ]
        then
            echo "webserver is running..."
        else
            echo "webserver is not running"
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
    esac
}

main $1

